### ISSUE TITLE
trumpet winsock?

### ISSUE THREAD

**Issue by stsp** [dosemu2/install-win31#13]
So what about installing
Trumpet and Netscape
communicator? :)

**Comment by jschwartzenberg** [comment]
I was thinking about Twinsock instead of Trumpet, but indeed it would seem nice to get networking too.

Do you think the unix side of Twinsock could be a dosemu plugin?

**Comment by stsp** [comment]
It could, but for now lets just
install Trumpet. Swapping the
2 would be simple.

**Comment by jschwartzenberg** [comment]
My main issue with Trumpet is that the original author is still selling the software and asking people to pay for it also when they still run it on Windows 3.1:
https://www.tattsoft.com/index.php/downloads

The other things these scripts fetch are not actively offered for sale by their original authors.

**Comment by jschwartzenberg** [comment]
It seems with the current version of dosemu2, [Ultra TwinSock](https://github.com/jschwartzenberg/twinsock/releases/tag/ultra-v0.2) works quite well, but the host binary needs to be in a place here the `dosemu2` user can find it.
The following works for me:
1. `cp utshost /tmp/`
2. Add a line to the configuration: `$_com4 = "exec /tmp/utshost"`
3. Run dosemu2 and start the Windows portion
4. Set the program to COM4
5. File -> Connect

The connection will be established.

Do you think we could incorporate this in some way?

**Comment by stsp** [comment]
I think we can provide a package
with the host part, and integrate it
on a doc level, asking the user to
configure the com port by hands.
Not how things are supposed to be
integrated, but good enough until
the proper tcp support is in.

Суббота, 15 марта 2025 г получено от Julius Schwartzenberg:

**Comment by stsp** [comment]
I can now build twinsock
with openwatcom:
https://github.com/stsp/owsock
Could you please check if
the resulting dll works as
expected? If so, I can start
porting it to dosemu2
sockets.

**Comment by stsp** [comment]
And to help your testing,
here's the dll:
[winsock.dll.gz](https://github.com/user-attachments/files/21559739/winsock.dll.gz)

**Comment by stsp** [comment]
Interesting.
This likely means a bad build.
Will get to this after fixing
windows problems with fdpp.

**Comment by stsp** [comment]
[winsock.dll.gz](https://github.com/user-attachments/files/21672584/winsock.dll.gz)
Here's probably a better build.

**Comment by stsp** [comment]
Sure, license.
I don't really care, as I am
going to port it on to my
socket impl. I just need
something to start from.

**Comment by stsp** [comment]
Yes, tomorrow's update
should be much faster
with win31.

So have you used original
dll or my dll?

**Comment by jschwartzenberg** [comment]
> So have you used original
> dll or my dll?

That was still with the original dll. I wanted to see it working at all first...

**Comment by stsp** [comment]
Ok I'll find the way to build
dlls with OW sometime. :)
What kind of hang?

**Comment by stsp** [comment]
https://github.com/stsp/twinsock
Got it to build, so see if
the problem is still there.

**Comment by stsp** [comment]
Hang should now be fixed.

**Comment by stsp** [comment]
It seems twinsock-1.4 works
reliably too, just as ultra. So
I don't think ultra fixed any
bug - it was just based on a
fixed version.

There is some problem with
select(). If I disable select(),
I am getting 1.2 stable too.

**Comment by jschwartzenberg** [comment]
> How to reproduce the hang?

For me it happens after using Ultra TwinSock for some time. I manage to connect with AIM and then start Netscape which sooner or later hangs the whole dosemu session and I have to do a ctrl+c from the terminal where I started dosemu.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by stsp** [comment]
[WINSOCK.DLL.gz](https://github.com/user-attachments/files/21936066/WINSOCK.DLL.gz)
Here's the next version of dll.
But please, no random things:
I only tested it with Netscape.

**Comment by jschwartzenberg** [comment]
This DLL gives me strange behavior. AIM immediately pops up ready to connect. Normally that only happens after I actually run the host binary from TwinSock.

TwinSock itself doesn't like the DLL either. When I run the host binary, it doesn't react and when I click Setup -> Connect manually, I get this:
<img width="840" height="669" alt="Image" src="https://github.com/user-attachments/assets/72a8d104-87dc-413c-adb4-70eb355c2ae0" />

**Comment by stsp** [comment]
Does Netscape also work?

**Comment by stsp** [comment]
> AIM immediately pops up ready to connect.

Does it connect?

**Comment by jschwartzenberg** [comment]
> Does Netscape also work?

Netscape does not die, but it doesn't end up connecting to anything. Is this DLL supposed to work without TwinSock?

> Does it connect?

It crashes after that. I can't even click the "Sign in" button.

**Comment by stsp** [comment]
I wonder why such a difference.
Is this netscape 4.08?
We probably should exchange
the images of drive_c to come
to some common denominator...

**Comment by jschwartzenberg** [comment]
> Also is your dosemu2 up-to-date
> with git?

I'm using the PPA here, I saw there was indeed an update:
```
Bezig met uitpakken van dosemu2 (2.0~pre9-9775-cffcd17d2+202508241316~ubuntu22.04.1) over (2.0~pre9-9762-674e27f11+202508210717~ubuntu22.04.1) ...
```

So I was missing some days. I understand this DLL should already work without TwinSock?

With the new version, starting Windows crashes:
```
[julius@elleboog ~]$ dosemu
ERROR: using outdated config file /home/julius/.dosemurc
Your kernel is too old, not using Landlock
ERROR: landlock_init() failed
ERROR: eVGAEmuFault: unimplemented decode instr at 7f0436662861: fca566f3
Terminated with signal 67
```

**Comment by stsp** [comment]
> I understand this DLL should already work without TwinSock?

Yes, I removed twinsock code
and renamed the project to
Open Winsock.

> Terminated with signal 67

Yes, reproducible...
So we have a non-functional
packages again. :(

**Comment by stsp** [comment]
Rebuilding now on LP.

**Comment by stsp** [comment]
Yep, feel free to remove,
thanks for testing.
It wasn't about that particular
issue - just 1 commit where
I changed some serial stuff.

**Comment by nelgin** [comment]
No problem. Tag me again if you need me to test. Thanks.

**Comment by jschwartzenberg** [comment]
New build from PPA works again! I added `$_com4 = "wrfile /tmp/dosemu-winsock.log"` to my `.dosemurc`. The entire terminal ends up being filled with: `ERROR: SER1: Invalid filedescriptor`.

[dosemu-winsock.log](https://github.com/user-attachments/files/21973901/dosemu-winsock.log)

Netscape AIM still dies  even before I can click on anything. Netscape doesn't seem to feel like loading anything.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by jschwartzenberg** [comment]
Those messages are not printed anymore indeed, but not much else changed. Do you have Netscape working there?

[dosemu-winsock.log](https://github.com/user-attachments/files/21993492/dosemu-winsock.log)

**Comment by stsp** [comment]
I think AIM is interfering.
Please disable everything
else that could you network,
and use ONLY netscape.

**Comment by jschwartzenberg** [comment]
Does not seem to make a difference. I also made the browser start with a blank page.
DNS lookup is not working:
<img width="840" height="669" alt="Image" src="https://github.com/user-attachments/assets/6e17e83c-01ed-448a-be30-ddc935f17dab" />
[dosemu-winsock.log](https://github.com/user-attachments/files/21993651/dosemu-winsock.log)

Maybe I'm still missing some fixes though. I saw the messages were still getting printed when the log file was not existing. I had to touch it before running dosemu to avoid the messages.

**Comment by stsp** [comment]
Are there any limitations
about DNS server in your
network? I hardcoded
"8.8.8.8" as DNS, can this
be a problem?

**Comment by stsp** [comment]
Ok, I added $_dnsserver and
$_ntpserver opts, so that you
no longer need to unblock
anything.

**Comment by jschwartzenberg** [comment]
It's not trivial to pick up what the system default is I guess?

**Comment by stsp** [comment]
Its rather trivial, although
for what? Only you block DNS.
Plus, there is currently the
large diversity of mechanisms:
NetworkManager, systemd etc.
Of course they still provide
/etc/resolv.conf as a fall-back,
so that's still trivial.

Its really only needed for you,
so the patch welcome. :)

**Comment by stsp** [comment]
Ok, done.
Now would you like to code
for openwinsock:
https://github.com/stsp/owinsock
This win16 stuff is absolutely
boring.

**Comment by stsp** [comment]
> First step would be to actually add the WinSock DLL right?

Not right.
You can add Video for Windows
at any time at all. As for the rest -
it can either be added (but won't
work for a moment), or can wait
in a form of PRs.

> Are any releases published?

Not yet, as I hate this win16
stuff, and openwinsock is very
rudimentary and wrongly
implemented. But it will be.
I already spent more than a
year on this silly TCP stuff, so
its inevitable. :)

> Would it make sense to create issues for any non-working network tool in the stsp/owinsock project?

Yes, just attach serial logs
and I'll see what functions are
missing then. Most of all are
missing, but nevertheless.

**Comment by jschwartzenberg** [comment]
> You can add Video for Windows
> at any time at all.

I looked a bit around. It seems Video for Windows was localized at least for some languages: http://www.win3x.org/win3board/viewtopic.php?t=115

I guess we could start with just an English version. I hope I can find an installer that doesn't require interaction. WinG seems similar btw.

**Comment by jschwartzenberg** [comment]
It seems that it's not obvious which version of Video for Windows is the latest. There are multiple versions that are "1.1e", but some of them are newer with newer codecs. Notably this one seems to be the newest: https://archive.org/download/complete-space-astronomy/Complete%20Space%20%26%20Astronomy%20-%20Disc%202.iso/IVI_WN31.EXE

When installing on a non-English Windows version, you end up with an extra Program Manager group Accessories containing just a Media Player icon, which points to the same program in the localized Program Manager group.

I don't know if there's a way to do a silent installation. The help text is a bit cryptic:
<img width="840" height="669" alt="Image" src="https://github.com/user-attachments/assets/0d69d27d-0108-4b1a-9634-3d1e4eca4853" />

**Comment by jschwartzenberg** [comment]
There was also a Japanese version: https://www.betaarchive.com/database/view_release.php?uuid=f3d9d070-4320-4642-91ff-8dc6d8f9a97c

**Comment by stsp** [comment]
Netscape seems to suggest
this one:
http://ftp.lanet.lv/ftp/windows/www/netscape3.0/wv1160.exe
Have you tried it?
In case of a non-interactive
setups, I think the best
solution is to just put the
setups in the Startup group,
and have the user handle
them later.
Maybe all software, but the
drivers you already install,
should be handled that way?

**Comment by jschwartzenberg** [comment]
> Netscape seems to suggest
> this one:
> http://ftp.lanet.lv/ftp/windows/www/netscape3.0/wv1160.exe
> Have you tried it?

No, I'll take a look at that one. I suspect almost all copies are the English version which means people end up with an English version of Media Player even on any non-English Windows.

Below some research on what is out there. It seems beyond English, there were common French and German versions. There is also a Japanese version. Everybody else had to settle with an English version of Media Player after installing Video for Windows. Maybe localized MS Office/PowerPoint versions will have a localized mplayer.exe, I'll still look at that. At least it seems easy enough to alter the setup files to remove the extra Program Manager group and icon.


Japanese versions: https://discmaster.textfiles.com/browse/1272/I Love Epson 1996.iso/pc/vfw11j
https://discmaster.textfiles.com/browse/10904/Escaper 4 - Disc 1.iso/disk1
https://discmaster.textfiles.com/browse/15810/Pet Room.iso/setup/vfw_rt

Japanese PC98 version: https://discmaster.textfiles.com/browse/29273/CD [BM9508].bin/programs/vfw_run
https://discmaster.textfiles.com/browse/13991/Legend of Seifuku (Platinum).iso/setup/vfw_rt

Official Microsoft discs with English, French and German VFW versions: https://archive.org/details/
Multimedia_Microsoft_Jumpstart_Version_1.1a_Microsoft https://discmaster.textfiles.com/browse/15103/Multimedia Microsoft Jumpstart Version 1.1a (Microsoft).BIN/develpmt/sdk/vfw11.win/runtime/disks

More CDs with those three languages: https://discmaster.textfiles.com/browse/13398/Hot Movies.iso/winvideo
https://discmaster.textfiles.com/browse/21818/Pegasus_Vol_5_CD2.iso/steinber/vfw.11
https://discmaster.textfiles.com/browse/29367/Visual_Basic_Multimedia_Adventure_Set_Coriolis_Group_1994.iso/vfw11a/runtime/disks
https://discmaster.textfiles.com/browse/23737/PCWorld_2001-08_cd.bin/Software/Komercni/BEDesktopPro/WINVIDEO

Some specific 928Movie accelerated version: https://discmaster.textfiles.com/view/33127/prog56_63.zip/prog56_63/PROG_62/V11D1.ZIP/README.TXT (I'm not sure  yet if this required specific hardware, there seems to be a special display driver included. Edit: this requires special hardware that's not detected in DOSEMU.)

Some graphics driver with a specific version that deals with scaling: https://discmaster.textfiles.com/browse/33907/pcpro-0497.iso/essentia.ls/drivers/videologic/graf500/GS5121D1.ZIP

German versions: https://discmaster.textfiles.com/browse/37708/Yellow Star Werbungs CD.iso/prog/zebok/demo/vfw
https://discmaster.textfiles.com/browse/7060/CDD_2_97.ISO/t-online/to_inst/avi
https://discmaster.textfiles.com/browse/14013/Let's Dance (1997)(KOCH).iso/VFW
https://discmaster.textfiles.com/browse/21768/PCS0396S.ISO/teamchef/vfw11e
https://discmaster.textfiles.com/browse/21070/PLANER.BIN/WORKSHOP/MS2TRIAL/DISK6/VFWSETUP
https://discmaster.textfiles.com/browse/22244/COMPUTER_CLUB_1094.BIN/zdemo/vfw
https://discmaster.textfiles.com/browse/22209/CLUB09_94.BIN/zdemo/vfw
https://discmaster.textfiles.com/browse/247/Bangkok 15.iso/vfw

French versions: https://discmaster.textfiles.com/browse/6923/cd.iso/vfw
https://discmaster.textfiles.com/browse/13960/Le monde de la mer.iso/pc/vfw
https://discmaster.textfiles.com/browse/38299/Villagina 4.dmg/SVMM_4/biblio/DEMOFOOT/DEMOFOOT.ZIP/DEMOFOOT/VFW
https://discmaster.textfiles.com/browse/36386/compatiblespcmagazine_numerocd100/compatiblespcmagazine_numerocd100/PCMAG100.iso/kitqdck/winvideo
https://discmaster.textfiles.com/browse/16065/PC Loisirs - Supplement Interactif No. 33 (France)/PC Loisirs - Supplement Interactif No. 33 (France).bin/VFW

Installers that embed their own VfW copy: https://discmaster.textfiles.com/browse/22786/PC_Advisor_July_1997.iso
https://discmaster.textfiles.com/browse/17171/TT3.ISO/pc/edinst
https://discmaster.textfiles.com/browse/12611/Corel Draw 5 CD2.iso/qtour/program
https://discmaster.textfiles.com/browse/22797/DISK19.iso/create/ereality/install/disk1
https://discmaster.textfiles.com/browse/13854/Kittens to Cats.iso

This one also embeds WinG: https://discmaster.textfiles.com/browse/35182/CD_ACTUAL_4.iso/edinst

Some larger media related thing which also contains VfW: https://discmaster.textfiles.com/browse/29649/ibm0310-0319/ibm0311.tar/ibm0311/Q-MEDIA2.ZIP

Brazilian discs are including an English version: https://discmaster.textfiles.com/browse/12161/Folha de SP 1994.iso/Unidade de DVD-RW (E_) FOLHA/VFWRNTM
https://discmaster.textfiles.com/browse/19577/Os Grandes Pintores Multimídia - Velázquez (PT-BR) (CCD).img/VFW
https://discmaster.textfiles.com/browse/19489/Enciclopédia Multimídia Da Arte Universal Vol. 8.img/VFWINST
https://discmaster.textfiles.com/browse/19577/Os Grandes Pintores Multimídia - Velázquez (PT-BR) (CCD).img/VFW
https://discmaster.textfiles.com/browse/22048/BigMax nº 18.iso/UTEIS/DISPLAY/BIG18.P01/uteis/vfw_11e

Polish disc with an English version: https://discmaster.textfiles.com/browse/23008/cdactioncoverdisc/zwierzak/setup/vfw

Includes some other larger mplayer version: https://discmaster.textfiles.com/browse/16348/Riki1296.iso/install

PowerPoint including a copy of VfW (maybe a source for localized versions): https://discmaster.textfiles.com/browse/38101/INSTALLER.iso/coffice4/power4/disk1

"JohnT - 11/15/94: added Brad's code to short-circuit restarting Windows.": https://discmaster.textfiles.com/browse/22041/BigMax nº 9 Curso de Excel 7.iso/VFW11D

**Comment by jschwartzenberg** [comment]
Regarding networking tools, hopefully we can get this one going once it's released ;)
https://mastodon.tmm.cx/@hp/115113887923223003

**Comment by stsp** [comment]
I brought the openwinsock
repo to some order. Its now
buildable by just running
`make`, given that `WATCOM`
var is set (all other vars,
including PATH, are now
auto-set).

So anyone interested, is
encouraged to at least
build it. :) Then I don't
have to put the new version
of DLL here every time.

Also I submitted the
networking fixes to
openwatcom, and they
are in. However they are
not needed for openwinsock
itself, as I am using a rip-off
of the sockets stack from
openwatcom codebase.

**Comment by stsp** [comment]
> @stefand do you know any
> restrictions on calling convention
> for win16 dll-exported funcs?

Ok, I figured this out now with
the help of @jmalak
It appears, any exported function
needs to have a special prolog:
```
        push            ds
        pop              ax
        nop
```
The loader scans the export table
looking for such prologs, and once
found - replaces it with `mov ax, dataseg`.
This is why OW insists on not
using AX in a calling convention
of an exported functions.
And this is why even the "callback"
functions normally exported only
via pointer, here must be exported
via the export table as well.

**Comment by jschwartzenberg** [comment]
> So anyone interested, is
> encouraged to at least
> build it. :) Then I don't
> have to put the new version
> of DLL here every time.

I just built it and it works great!!! No need to publish DLLs anymore for now. We should automate something for the scripts to fetch at some point though.


> adding Netscape 4.08

Just took a look at its installer, but it seems it cannot be trivially automated. Maybe some other browser/networking tool would be more interesting and practical to deploy...

**Comment by stsp** [comment]
> I just built it and it works great!!!

So you dealt with git
submodules and OW?
Congrats. :)

> We should automate something for the scripts to fetch at some point though.

Oh well, not sure if
@andrewbird will be so
keen to add OW into CI. :)

> Just took a look at its installer, but it seems it cannot be trivially automated.

But as I already mentioned
earlier, you only need to
install video for windows,
and put the netscape installer
into a startup group, so that
the user is to install it later.

> Maybe some other browser/networking tool would be more interesting and practical to deploy...

I am working on supporting IE.
With some hacks I've already
seen it does much, much better
job that netscape.
But we can install both, anyway.

**Comment by jschwartzenberg** [comment]
> So you dealt with git
> submodules and OW?
> Congrats. :)

Yep, I remembered the submodules commands :) I'll look into creating a PR for a README ;)
But the first time I ran `make` after setting the `WATCOM` variable I had a DLL, so the process is quite straightforward.


> But as I already mentioned
> earlier, you only need to
> install video for windows,
> and put the netscape installer
> into a startup group, so that
> the user is to install it later.

I was thinking that maybe we could get one browser installed automatically we might be able to either:
- Provide a nice set of default bookmarks to get more stuff
- Set its homepage to a page where users could quickly find and download more tools like this

Downloading and leaving behind various installers seems less optimal.


> I am working on supporting IE.
> With some hacks I've already
> seen it does much, much better
> job that netscape.
> But we can install both, anyway.

Ah nice! I think there's also a version of Opera avaiable.

**Comment by stsp** [comment]
> Downloading and leaving behind various installers seems less optimal.

But its till better than not
doing anything "because
the process cannot be batched".

Although I still wonder if the
startup solution is feasible:
we somehow need to _remove_
the installer from the startup
group after the installation...

Can IE be automated?

> Ah nice! I think there's also a version of Opera avaiable.

Does it support unicode?
IE doesn't, and the charsets
like koi8-r or 1251 that it has
for Cyrillic, are not used by
sites.

**Comment by andrewbird** [comment]
> Oh well, not sure if
@andrewbird will be so
keen to add OW into CI. :)

I already did it by hand for linux CI to build freecom and freedos kernel, but I believe there's a cross platform way using an action, but I didn't try it. Seems to be as simple adding this step see https://github.com/FDOS/freecom/blob/master/.github/workflows/ci-build.yml
~~~
- name: Open Watcom install
      uses: open-watcom/setup-watcom@v0
      with:
        version: ${{matrix.ow.id}}
~~~
Only downsides I can see with that is it seems like you can't run the tests outside of the CI environment, and of course it's tied to Github.

**Comment by stsp** [comment]
> Only downsides I can see with that is it seems like you can't run the tests outside of the CI environment

Why do I even need that?
We always run tests inside
CI, don't we?

> and of course it's tied to Github.

All we need here, is to get
the build of winsock.dll.
Nothing else is needed.

**Comment by andrewbird** [comment]
>> Only downsides I can see with that is it seems like you can't run the tests outside of the CI environment

> Why do I even need that?
We always run tests inside
CI, don't we?

You may not, I like to run tests locally (on other projects, install-win31 is outside of my interest).

> All we need here, is to get
the build of winsock.dll.
Nothing else is needed.

Cool.

**Comment by stsp** [comment]
So after `uses: open-watcom/setup-watcom@v0`
how should I set WATCOM
variable? Or is this step sets
it too?

**Comment by andrewbird** [comment]
> Or is this step sets
it too?

I don't know, as the script `build.sh` sets it if it's not set already, so it's unclear just from reading. As I mentioned it's not something I've used myself. Perhaps there's some documentation on https://github.com/open-watcom/open-watcom-v2 , though I did a quick look but didn't see anything. In a bit of a rush this morning, so won't be around for a bit.

**Comment by stsp** [comment]
Got it to work!
https://stsp.github.io/owinsock/

**Comment by jmalak** [comment]
> So after `uses: open-watcom/setup-watcom@v0` how should I set WATCOM variable? Or is this step sets it too?

It setup PATH, WATCOM and INCLUDE environment variable (same as OW installer) for host by default, if you need different target then you need specify.
setup-watcom@v0 install selected Open Watcom version on host system and setup OW environment that you need not to change anything.
the parameter is "target" when you can specify one of **`["", "dos", "win", "nt", "os2", "os2-16", "linux"]`**.
blank means default host

**Comment by stsp** [comment]
Yeah, had to specify "win" target,
as otherwise it sets up linux target,
which looks like a strange default
for ow. :)

Thanks!

Среда, 15 октября 2025 г получено от Jiří Malák:

**Comment by jmalak** [comment]
No OW installer do same thing configure OW for host system by default, you must change to different target if you need during installation. 
But you can simply change target dynamically by INCLUDE variable to point to headers relevant for selected target, nothing more.
If you want create portable makefile for **`cross-compile`** then you should setup always INCLUDE variable and not relate to default which is different on each host.

**Comment by stsp** [comment]
> If you want create portable makefile for cross-compile then you should setup always INCLUDE
> variable and not relate to default which is different on each host.

But this means I have
to ignore the provided
INCLUDE.
If INCLUDE is not provided,
I already set up my own.

**Comment by jmalak** [comment]
we are talking about portable makefile then you can use INCLUDE variable because it is used by compiler for searching standard headers. Take into account that you are cross-compile because you want to use single makefile on any host and on any OW configuration that you must control -bt=... and INCLUDE variable in dependency on target to which you cross-compile. Of cause you can rely on OW default configuration then you need to specify that OW is install on some host but for exact target (not default target) and you need not setup anything because you have by default setup for proper target then you use only -bt=.. for compiler but need not change INCLUDE because it is setup for correct target already. But if you cross-compile for multiple targets by single make file then no other way then -bt=.. and INCLUDE change together.

look on Wiki page which describe setup for cross-compilation of any OW compiler etc.
https://github.com/open-watcom/open-watcom-v2/wiki/OW-tools-usage-Overview

**Comment by stsp** [comment]
So if you suggest to
override INCLUDE because
of the cross-compilation,
then I can do that.
But it looks like in wcc
you can find the needed
include path yourself, based
on the specified `-bt=`,
when INCLUDE is not
set at all?

**Comment by jmalak** [comment]
Yes there is possibility to use variables `<os>_INCLUDE` where `<os>` is argument for `-bt=<os>` then you need not setup `INCLUDE` (only clean it). But it is more advanced configuration for cross-compilation and need to use it properly in makefiles.
`<os>_INCLUDE` is used before `INCLUDE`. Details are described in OW documentation 

https://open-watcom.github.io/open-watcom-v2-wikidocs/cguide.html#btUEXosYV

then you can use only `-bt=..` to control both `-bt` and `INCLUDE` by `-bt` option.
OW has various possibility how you can do it that optimal solution depend on what targets are used for your project and what variants etc. and what method you will use to switch target to do it properly because target doesn't means only OS but also by example if it is static library or DLL or single/multi-threaded application.
As example you can defile environment variable in makefile
DOS_INCLUDE=%WATCOM%\h
WINDOWS_INCLUDE=%WATCOM%\h;%WATCOM%\h\win
....
and switch it by 
-bt=dos
-bt=windows

Of cause there are other posibility to control it but then it is your responsibility to setup all correctly. By example you can use option -x and -xx and then you need to do all control on command line explicitly because these options ignore any environment variable used by compiler.
It is interresting that people want control anything and then create issue by incorrect use of such features even if there is more safer methods with using more transparent methods.

Anyway for such setup you can use wmake directives

**`.BEFORE`**
here you can setup new INCLUDE and other global setup

and 
**`.AFTER`**
here you can do anything what you need it be run as last

**Comment by stsp** [comment]
Ok, I did the override as
you suggested. But I don't
find it an ideal solution,
because besides setting
WINDOWS_INCLUDE I
also need to override the
INCLUDE set by github
action. It is set to h/win
when the target is properly
configured, but even in
that case I need to redefine
it to `h` and set
WINDOWS_INCLUDE to
h/win instead.

Why don't you consider the
possibility of automatically
setting platform-specific
include to h/`-bt=` dir?
Then the one only needs
to set -bt= correctly, and
everything else is done
automatically.

**Comment by jmalak** [comment]
If you build only for single target then override of INCLUDE is best solution.
Only if you build for multiple different targets then has sense to use ..._INCLUDE

By example for 16-bit Windows only solution wmake directive which do it

```
.BEFORE
    set INCLUDE=$(%WATCOM)/h;$(%WATCOM)/h/win
```

that on begining it overwrite INCLUDE by your value with respect of current OW location $(%WATCOM)
and you need not handle standard headers search any way.


Anyway WATCOM and OPEN WATCOM is open for user as much as possible.

By example **`-bt=<os>`** value can be anything and compiler works with it without problem
Compiler take bt **`<os>`** value and always create macro

**`__<os>__`** where **`<os>`** is uppercased

and use 

**`<os>_INCLUDE`** environment variable to search standard headers       where **`<os>`** is uppercased

Compiler doesn't do any other change if you change -bt option.
there are a few predefined values related to know OS-es that compiler generate some additional macros for these targets (required by example by ABI), but generaly you can use any value for **`<os>`** ID.

Anyway many people are from GNU world and expect that Open Watcom must behave same way, but OW has different approach because OW is cross-compiler by nature, you don't need install some special version or reinstall it to support cross-compilation.
-bt option is not any switch it only change ID used by your application that you can use it how you need, that your headers can use guards for your ID etc. Some switching is too closed functionality and therefore it is not used by WATCOM and Open Watcom all what you need can depend on ID passed by -bt option, you can deside how you will use this ID.
the same for linker there are not any meaning for system ID you can use any, there is configuration file which hold some predefined values, but it can be fully changed it is not hard-coded into linker.

**Comment by stsp** [comment]
Then why github action
can't set INCLUDE and all
xxx_INCLUDE to their
desired values?
Then:
- no need to specify target
- no need to override any var

**Comment by jmalak** [comment]
You want some type of configuration but other users want different.
If we are talking about watcom_setup then it behave same way as installer
You can setup what you need but make file must be able work on standard installation otherwise it has no sense.
Therefore setup_watcom install all binaries and setup PATH for host OS binaries
WATCOM is also setup to correct location, it uses some default path but you can specify it exactly
INCLUDE is setup by default for host OS, but you can specify different system.

..._INCLUDE is not specified because it has no sense we don't know what user will do etc.
If user want use ..._INCLUDE then it is his responsibility how and what setup.

I updated watcom_setup doc that now describe all parameters

```
name: 'Setup Open Watcom'
description: 'Setup an Open Watcom environment'
inputs:
  version:
    description: 'Open Watcom version: choices = [1.8, 1.9, 2.0, 2.0-64]'
    required: false
    default: '2.0'
  tag:
    description: 'Tag of snapshot to use: current, last or date. (only used for 2.0)'
    required: false
    default: ''
  location:
    description: 'Location where Open Watcom should be extracted to (default=$HOME/watcom or %USERPROFILE%\\WATCOM)'
    required: false
    default: ''
  environment:
    description: 'Set default Open Watcom environment variables (WATCOM + INCLUDE + PATH)'
    required: false
    default: true
  target:
    description: 'Set target OS (one of values "", "dos", "win", "nt", "os2", "os2-16", "linux"), change header search path (INCLUDE)'
    required: false
    default: ''

```

The problem is that you don't distinct between default and exact.
If you don't specify -bt option by example then default ID is used. Default ID is derived during run-time from host OS.
here is code which setup this default ID

```
    if( target_name == NULL ) {
#if defined( __NOVELL__ )
        SetTargetName( &target_name, "NETWARE" );
#elif defined( __QNX__ )
        SetTargetName( &target_name, "QNX" );
#elif defined( __LINUX__ )
        SetTargetName( &target_name, "LINUX" );
#elif defined( __HAIKU__ )
        SetTargetName( &target_name, "HAIKU" );
#elif defined( __SOLARIS__ ) || defined( __sun__ )
        SetTargetName( &target_name, "SOLARIS" );
#elif defined( __OSX__ ) || defined( __APPLE__ )
        SetTargetName( &target_name, "OSX" );
#elif defined( __OS2__ )
        SetTargetName( &target_name, "OS2" );
#elif defined( __NT__ )
        SetTargetName( &target_name, "NT" );
#elif defined( __DOS__ )
        SetTargetName( &target_name, "DOS" );
#elif defined( __BSD__ )
        SetTargetName( &target_name, "BSD" );
#elif defined( __RDOS__ )
        SetTargetName( &target_name, "RDOS" );
#else
        #error cmdlx86.c - Target OS not defined
#endif
    }
```

The default is host OS that it can be different on each OW installation, but if you want compile for exact system then you must specify it explicitly. Therefore -bt must be used always if you cross-compile but not if you compile for host OS.

If you use watcom_setup to compile for 16-bit Windows then you should use following call

```
- uses: open-watcom/setup-watcom@v0
  with:
    version: "2.0"
    target:  "win"
```

But it doesn't mean that you can relate to Windows as default, you must use -bt because you are cross compiling.
INCLUDE is setup for 16-bit Windows.

**Comment by stsp** [comment]
I added some IE support.
But it doesn't looks like the
one can gain much. Oh well
it does display goto95.com
and even vogons.org to some
extent, but there is nothing
really functional.

Also I've found that Netscape
crashes on vogons.org, and
it may be a Netscape bug or
my bug.

@jschwartzenberg so what
do you think? Can you do some
more testing and find out if
maybe Opera works better,
or whether or not Netscape
crashes with twinsock?

**Comment by jschwartzenberg** [comment]
> Oh well
> it does display goto95.com
> and even vogons.org to some
> extent, but there is nothing
> really functional.

Indeed most sites won't be working but there are sites targeting older browsers. This is why I propose shipping some bookmarks or maybe a basic html page with links to compatible sites. A good one is for instance http://www.wiby.org/ another one http://www.chivanet.org/


> Also I've found that Netscape crashes on vogons.org, and it may be a Netscape bug or my bug.
> 
> [@jschwartzenberg](https://github.com/jschwartzenberg) so what do you think? Can you do some more testing and find out if maybe Opera works better, or whether or not Netscape crashes with twinsock?

I'll see if I can reproduce this crash with twinsock. I am struggling to find time...

**Comment by jschwartzenberg** [comment]
Seems the crash is identical with Ultra TwinSock:
<img width="840" height="669" alt="Image" src="https://github.com/user-attachments/assets/02d77ced-b1c7-40d2-8789-0555189dcc70" />

**Comment by jschwartzenberg** [comment]
Here are some versions of Opera, but I cannot get them to run: http://www.win3x.org/win3board/viewtopic.php?t=2636&view=min

Opera 2.12 installs, but running it crashes dosemu2.
Running the Opera 3.62 installer crashes dosemu2.

**Comment by stsp** [comment]
Have you got success with IE?
